### ISSUE TITLE
运行encrypt.py报错ValueError: Incorrect AES key length (33 bytes)

### ISSUE THREAD

**Issue by XeonChow** [li1553770945/NUAA-Check#4]
老哥您好，运行`encrypt.py`对`data.txt`加密的时候，报错`ValueError: Incorrect AES key length (33 bytes)`，我确定创建的`key.txt`文件里是个32位的字符串，`key.txt`里删掉一个字符再运行`encrypt.py`可以成功，但是在GitHub action里运行就会报错`ValueError('Incorrect AES key length (31 bytes)')`，对AES加密的库不太了解，您看看能否解决。运行`encrypt.py`完整结果如下：
```
Traceback (most recent call last):
  File "/mnt/c/Users/Xeon/NUAA-Check/encrypt.py", line 34, in <module>
    AES_encrypt(key, data)
  File "/mnt/c/Users/Xeon/NUAA-Check/encrypt.py", line 9, in AES_encrypt
    cipher = AES.new(key.encode('utf8'), AES.MODE_CBC, vi.encode('utf8'))
  File "/home/xeon/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/xeon/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/xeon/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/home/xeon/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (33 bytes)
```

**Comment by XeonChow** [comment]
> 你方便把你的key发出来么（之后记得不要用这个），我没遇到这样的问题，我猜你是不是里面有中文符号或者其他字符？然后因为编码不同的原因造成了不同长度。

我使用的key是`xduPn2bhL42HiKzThysaAaMm4dmWrJO3`，应该没有中文字符啥的，用随机字符串生成器生成的，文件编码是utf-8

**Comment by li1553770945** [comment]
我刚试了下没有问题，不过我发现末尾如果有空格或者换行都会报错，你是不是多打了空格或者换行呢
![image](https://user-images.githubusercontent.com/55867654/168588316-95d21f85-f5c2-437c-8514-f535577c2225.png)
![image](https://user-images.githubusercontent.com/55867654/168588360-6aef717d-3f4e-412f-acd0-ea5b2fa5a00f.png)

**Comment by XeonChow** [comment]
> xduPn2bhL42HiKzThysaAaMm4dmWrJO3

多谢，我一开始用的vim创建的`key.txt`，看起来既没有空格也没有换行，后来用vscode打开一看真的有个换行，估计是CRLF和LF之类的问题，现在可以了。

**Comment by li1553770945** [comment]
恩恩不客气，应该是windows和linux换行符不一致导致的，我写个if判断一下，如果字符串长于32个字符就截断好了。
